# Create a Pod with main container busybox and which executes this “while true; 
# do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep 5; done” 
# and with sidecar container with nginx image which exposes on port 80. 
# Use emptyDir Volume and mount this volume on path /var/log for busybox 
# and on path /usr/share/nginx/html for nginx container. Verify both 
# containers are running.

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: frontend
  name: main
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/log/
      name: shared-volume
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
         echo "Hi I am from Main container" >> /var/log/index.html;
          sleep 5;
        done
  - image: nginx
    name: sidecar-nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-volume
    