---
# # Create a Pod with three busy box containers with commands “ls; sleep 3600;”, 
# # “echo Hello World; sleep 3600;” and “echo this is the third container; sleep 3600” 
# # respectively and check the status

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: frontend
  name: task1
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ["/bin/sh", "-c"]
    args: [ls; sleep 3600;]

  - image: busybox
    name: busybox2
    command: ["/bin/sh", "-c"]
    args: ["echo Hello World; sleep 3600;"]

  - image: busybox
    name: busybox3
    command: ["/bin/sh", "-c"]
    args: ["echo this is the third container; sleep 3600"]


