apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    type: frontend
  name: testpo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: frontend
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: frontend
  name: testpo
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-volume
  - image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /html
      name: shared-volume
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done